### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ronrihoo** [abgier-avraha/Banipal-Assyrian-Dictionary-Website#1]
Thank you for this awesome project. Please add a license, so that we may know whether we can use any part of it.

Also, in the README, please add info about whether the dictionary dataset is free to use outside of this project.

Thanks again.

**Comment by abgier-avraha** [comment]
Ah yes, this definitely should have been addressed earlier.
I just added the license information in a text file and an explanation of the license within the readme. Everything falls under an MIT license including the dictionary dataset.
